### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by RooflOmg** [wu452148993/wurst#1]
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.10.3/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'wurst'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve net.minecraftforge.gradle:ForgeGradle:3.+.
     Required by:
         project :
      > Failed to list versions for net.minecraftforge.gradle:ForgeGradle.
         > Unable to load Maven meta-data from https://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/maven-metadata.xml.
            > Could not get resource 'https://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/maven-metadata.xml'.
               > Could not GET 'https://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/maven-metadata.xml'.
                  > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Failed to list versions for net.minecraftforge.gradle:ForgeGradle.
         > Unable to load Maven meta-data from https://dist.creeper.host/Sponge/maven/net/minecraftforge/gradle/ForgeGradle/maven-metadata.xml.
            > Could not get resource 'https://dist.creeper.host/Sponge/maven/net/minecraftforge/gradle/ForgeGradle/maven-metadata.xml'.
               > Could not GET 'https://dist.creeper.host/Sponge/maven/net/minecraftforge/gradle/ForgeGradle/maven-metadata.xml'.
                  > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve org.spongepowered:mixingradle:0.7-SNAPSHOT.
     Required by:
         project :
      > Could not resolve org.spongepowered:mixingradle:0.7-SNAPSHOT.
         > Unable to load Maven meta-data from https://files.minecraftforge.net/maven/org/spongepowered/mixingradle/0.7-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://files.minecraftforge.net/maven/org/spongepowered/mixingradle/0.7-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://files.minecraftforge.net/maven/org/spongepowered/mixingradle/0.7-SNAPSHOT/maven-metadata.xml'.
                  > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve org.spongepowered:mixingradle:0.7-SNAPSHOT.
         > Unable to load Maven meta-data from https://dist.creeper.host/Sponge/maven/org/spongepowered/mixingradle/0.7-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://dist.creeper.host/Sponge/maven/org/spongepowered/mixingradle/0.7-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://dist.creeper.host/Sponge/maven/org/spongepowered/mixingradle/0.7-SNAPSHOT/maven-metadata.xml'.
                  > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s

**Comment by benj0670** [comment]
Please see my fork for updated repo links that fix this error

**Comment by wu452148993** [comment]
Sorry, there are many things I have forgotten about this project recently

**Comment by wu452148993** [comment]
PKIX path building failed is SSL ERROR.You can refer to the following plan:
(source:https://stackoverflow.com/questions/9619030/resolving-javax-net-ssl-sslhandshakeexception-sun-security-validator-validatore)

You need to add the certificate for these websites to the truststore file of the used JVM located at %JAVA_HOME%\lib\security\cacerts.

First you can check if your certificate is already in the truststore by running the following command: keytool -list -keystore "%JAVA_HOME%/jre/lib/security/cacerts" (you don't need to provide a password)

If your certificate is missing, you can get it by downloading it with your browser and add it to the truststore with the following command:

keytool -import -noprompt -trustcacerts -alias <AliasName> -file   <certificate> -keystore <KeystoreFile> -storepass <Password>

Example:
keytool -import -noprompt -trustcacerts -alias myFancyAlias -file /path/to/my/cert/myCert.cer -keystore /path/to/my/jdk/jre/lib/security/cacerts/keystore.jks -storepass changeit

After import you can run the first command again to check if your certificate was added.

Sun/Oracle information can be found here:https://docs.oracle.com/javase/tutorial/security/toolsign/rstep2.html
